library(oro.dicom)

#setwd("/Users/lucychen/Documents/Lab/NIHLab/DicomData")
fname <- system.file(file.path("dcm","/Users/lucychen/Documents/Lab/NIHLab/DicomData/test.dcm"), package="oro.dicom")
#print(type(fname))
print(fname)
abdo <- readDICOMFile("/Users/lucychen/Documents/Lab/NIHLab/DicomData/test.dcm")
print(names(abdo))
#print((abdo$hdr))
timeStart <- extractHeader(abdo$hdr, "AcquisitionTime")
print(typeof(timeStart))
print(timeStart)
timeStart<- toString(timeStart)
timeStartTime <- strptime('26/jun/2018:15:51:00',format='%d/%b/%Y:%H:%M:%S')
print(timeStartTime)
newTime <- as.POSIXct(timeStart,format='%H%M%S')
newTime <- format(newTime, tz="UTC",usetz=TRUE)
newTime <- difftime(timeStartTime, newTime)
print(newTime)

